version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: gophkeeper_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${PRIVATE_KEY_PATH}:/root/.minio/private.key
      - ${PUBLIC_KEY_PATH}:/root/.minio/public.crt
      - minio_data:/data
    command: server /data --console-address ":9001" --certs-dir /root/.minio

  postgresql:
    image: postgres:latest
    container_name: gophkeeper_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  minio_data:
