name: Build ubuntu

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Build server
        run: go build -o gophkeeper-server -v ./cmd/server/

      - name: Build client
        run: go build -o gophkeeper-client -v ./cmd/client/

      - name: Archive server artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: gophkeeper-server-ubuntu-artifact
          path: gophkeeper-server

      - name: Archive client artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: gophkeeper-client-ubuntu-artifact
          path: gophkeeper-client