name: Build windows

on:
  workflow_run:
    workflows: ["Checks-and-tests"]
    types:
      - completed

jobs:
  build-windows:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Build server
        run: go build -o gophkeeper-server -v ./cmd/server/

      - name: Build client
        run: go build -o gophkeeper-client -v ./cmd/client/

      - name: Archive server artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: gophkeeper-server-windows-artifact
          path: gophkeeper-server

      - name: Archive client artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: gophkeeper-client-windows-artifact
          path: gophkeeper-client