name: Checks-and-tests

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio
        ports:
          - "9000:9000"
          - "9001:9001"
        env:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        volumes:
          - minio_data:/data
          - ${{ github.workspace }}/certs:/root/.minio
        command: server /data --console-address ":9001" --certs-dir /root/.minio
        options: >-
          --health-cmd="curl --silent --fail https://localhost:9000/minio/health/live" 
          --health-interval=30s 
          --health-timeout=5s 
          --health-retries=3

      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=30s 
          --health-timeout=5s 
          --health-retries=3

    volumes:
      minio_data:

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Build server
        run: go build -o gophkeeper-server -v ./cmd/server/

      - name: Build client
        run: go build -o gophkeeper-client -v ./cmd/client/

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
