name: BuildAndCheck

on:
  push:
    branches: [*]
  pull_request:
    branches: [*]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Build server
        run: go build -o gophkeeper-server -v ./cmd/server/

      - name: Build client
        run: go build -o gophkeeper-client -v ./cmd/client/

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -race -vet=off ./...

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23

      - name: Verify dependencies
        run: go mod verify

      - name: Build server
        run: go build -o gophkeeper-server-amd64 -v ./cmd/server/

      - name: Build client
        run: go build -o gophkeeper-client-amd64 -v ./cmd/client/

      - name: Archive server artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: gophkeeper-server-amd64-artifact
          path: gophkeeper-server-amd64

      - name: Archive client artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: gophkeeper-client-amd64-artifact
          path: gophkeeper-client-amd64